import type { Language } from "./languages";

type Props={language:Language};
type Card={title:string;serial:string;text:string;hint:string;icon:string};

const EN={eyebrow:"Universal serial guide",title:"How to find the serial on common factory radios",intro:"There is no single serial format for every car. Start with the method that matches the radio family, copy every character exactly, and use the matcher above to narrow the possibilities.",warning:"Do not enter random unlock codes just to test the radio. ERR, SAFE, WAIT and LOCK messages usually mean the unit is counting failed attempts, and additional guesses can increase the lockout time.",safety:"If the serial is on the radio casing and the unit must be removed, use the correct release tools or ask an installer if trim panels, wiring or airbags are nearby.",cta:"I found my serial — go to the request form →"};
const ES={eyebrow:"Guía universal de series",title:"Cómo encontrar la serie en radios originales comunes",intro:"No existe un solo formato de serie para todos los carros. Empieza con la familia que se parezca a tu radio, copia todos los caracteres exactamente y usa el identificador de arriba para reducir las opciones.",warning:"No introduzcas códigos de desbloqueo al azar para probar. ERR, SAFE, WAIT y LOCK normalmente indican intentos fallidos; seguir adivinando puede aumentar el tiempo de bloqueo.",safety:"Si la serie está en la carcasa y hay que desmontar el radio, usa las herramientas correctas o pide ayuda a un instalador si hay molduras, cableado o bolsas de aire cerca.",cta:"Ya encontré mi serie — ir al formulario →"};

const cardsEN:Card[]=[
 {icon:"H",title:"Honda / Acura — on-screen serial",serial:"U2154 L2135 · S/N 2602353",text:"On many older Honda/Acura units, leave the radio off, hold presets 1 and 6, then press PWR/VOL. Compatible radios can display U/L groups or an S/N.",hint:"Touchscreen and navigation units may use a service-information screen instead. If the screen does not match, use the label or the instructions for that exact head unit."},
 {icon:"F",title:"Ford / Visteon",serial:"V123456 · M123456 · C7…",text:"Many older Ford radios can show a V- or M-series serial on screen, commonly by holding 1 + 6 or 2 + 6 depending on the unit. TravelPilot/Blaupunkt families can use C7 or BP prefixes.",hint:"M-series can also appear on some older Land Rover/Visteon radios, so confirm the vehicle or radio label."},
 {icon:"VW",title:"Volkswagen Group",serial:"VWZ… · AUZ… · SEZ… · SKZ…",text:"Volkswagen, Audi, SEAT and Škoda factory radios often carry a distinctive serial on the top or side label of the unit. The prefix usually identifies the vehicle brand.",hint:"These codes are generally database-linked; the serial format identifies the family but is not itself the unlock code."},
 {icon:"N",title:"Nissan / Clarion / Blaupunkt / Visteon",serial:"CL… · PN… · PP… · BP… · DW…",text:"Nissan used several radio suppliers. Some serials are on a rear label; others appear in radio information screens. Certain families also need a model, device/part number or date.",hint:"If the screen shows several identifiers, photograph all of them instead of copying only one number."},
 {icon:"R",title:"Renault / Dacia",serial:"A123 · 2811… · 8200… · 7700…",text:"Older units can use a four-character precode. Other Renault/Dacia radios place a longer identifier on the casing label, while some newer systems are paired to the vehicle instead of using a typed radio code.",hint:"Do not confuse a part number with the security/precode field; copy the complete labeled identifier."},
 {icon:"C",title:"Continental / Bosch / Blaupunkt shared families",serial:"A2C… · A3C… · 815CM… · BP…",text:"These supplier prefixes appear across Fiat, Alfa Romeo, Lancia, Peugeot, Citroën and other vehicles. The radio manufacturer can be identified, but the vehicle badge may remain ambiguous.",hint:"This is exactly why the serial matcher can return more than one vehicle option."},
 {icon:"J",title:"Jeep / Chrysler / Dodge Uconnect",serial:"T00AM… · T19QN… · TVPQN… · TZ1AA…",text:"Shared T-series radios are used across Jeep, Chrysler and Dodge. Long Continental A2C identifiers also appear on some units.",hint:"A T-series serial can identify the radio platform without uniquely identifying which of the three vehicle brands it came from."},
 {icon:"MB",title:"Mercedes / Becker / Alpine",serial:"BE… · AL… · MF…",text:"Older Mercedes and Becker-family radios usually have the serial on the casing label. Becker units commonly use BE plus model/unit digits; older Alpine/Audio units can use AL or MF prefixes.",hint:"Later COMAND/Audio systems may use diagnostic pairing rather than a simple user-entered radio code."},
 {icon:"T",title:"Toyota / Lexus ERC and other numeric serials",serial:"16-character ERC · 7/8-digit serials",text:"Some Japanese-market Toyota/Lexus head units display a 16-character ERC. Plain 7- or 8-digit serials occur in several other manufacturers too, so length alone is not enough to identify a car.",hint:"When a number has no distinctive prefix, include the radio manufacturer, model label or a clear photo for manual verification."},
];

const cardsES:Card[]=[
 {icon:"H",title:"Honda / Acura — serie en pantalla",serial:"U2154 L2135 · S/N 2602353",text:"En muchos Honda/Acura antiguos, deja el radio apagado, mantén 1 y 6 y después presiona PWR/VOL. Las unidades compatibles pueden mostrar grupos U/L o un S/N.",hint:"Las pantallas táctiles y unidades de navegación pueden usar un menú de información de servicio. Si tu pantalla no coincide, usa la etiqueta o la guía de esa unidad."},
 {icon:"F",title:"Ford / Visteon",serial:"V123456 · M123456 · C7…",text:"Muchos Ford antiguos muestran series V o M en pantalla, normalmente manteniendo 1 + 6 o 2 + 6 según la unidad. Las familias TravelPilot/Blaupunkt pueden usar C7 o BP.",hint:"La serie M también aparece en algunos Land Rover/Visteon antiguos; confirma el vehículo o la etiqueta."},
 {icon:"VW",title:"Grupo Volkswagen",serial:"VWZ… · AUZ… · SEZ… · SKZ…",text:"Los radios originales Volkswagen, Audi, SEAT y Škoda suelen llevar una serie distintiva en la etiqueta superior o lateral. El prefijo normalmente indica la marca.",hint:"Estas familias suelen depender de una base de datos; la serie identifica la unidad, pero no es el código de desbloqueo."},
 {icon:"N",title:"Nissan / Clarion / Blaupunkt / Visteon",serial:"CL… · PN… · PP… · BP… · DW…",text:"Nissan utilizó varios fabricantes. Algunas series están en la etiqueta trasera y otras aparecen en pantallas de información. Algunas familias también requieren modelo, número de dispositivo/pieza o fecha.",hint:"Si la pantalla muestra varios datos, toma una foto de todos en lugar de copiar solo uno."},
 {icon:"R",title:"Renault / Dacia",serial:"A123 · 2811… · 8200… · 7700…",text:"Las unidades antiguas pueden usar un pre-código de cuatro caracteres. Otras llevan una serie más larga en la etiqueta, y algunos sistemas nuevos quedan vinculados al vehículo en lugar de usar un código escrito.",hint:"No confundas el número de pieza con el campo de seguridad o pre-código; copia el identificador completo."},
 {icon:"C",title:"Familias compartidas Continental / Bosch / Blaupunkt",serial:"A2C… · A3C… · 815CM… · BP…",text:"Estos prefijos aparecen en Fiat, Alfa Romeo, Lancia, Peugeot, Citroën y otras marcas. Podemos reconocer al fabricante del radio, pero la marca del vehículo puede seguir siendo ambigua.",hint:"Por eso nuestro identificador puede devolverte más de una opción de vehículo."},
 {icon:"J",title:"Jeep / Chrysler / Dodge Uconnect",serial:"T00AM… · T19QN… · TVPQN… · TZ1AA…",text:"Los radios de serie T se comparten entre Jeep, Chrysler y Dodge. Algunas unidades también utilizan identificadores Continental A2C largos.",hint:"Una serie T puede identificar la plataforma del radio sin decir de forma única cuál de las tres marcas de vehículo la utilizó."},
 {icon:"MB",title:"Mercedes / Becker / Alpine",serial:"BE… · AL… · MF…",text:"Los Mercedes antiguos y radios Becker suelen tener la serie en la etiqueta de la carcasa. Becker usa normalmente BE más números de modelo/unidad; algunas unidades Alpine/Audio usan AL o MF.",hint:"Sistemas COMAND/Audio posteriores pueden usar emparejamiento por diagnóstico en vez de un código que el usuario escriba."},
 {icon:"T",title:"Toyota / Lexus ERC y series numéricas",serial:"ERC de 16 caracteres · series de 7/8 dígitos",text:"Algunas unidades Toyota/Lexus del mercado japonés muestran un ERC de 16 caracteres. Las series numéricas de 7 u 8 dígitos aparecen también en otras marcas, así que la longitud sola no identifica el carro.",hint:"Si no existe un prefijo distintivo, incluye fabricante/modelo del radio o una foto clara para revisión manual."},
];

export default function ExpandedSerialGuide({language}:Props){
 const es=language==="es";
 const h=es?ES:EN;
 const cards=es?cardsES:cardsEN;
 return <section id="serial-help" className="scroll-mt-28 border-y border-slate-200 bg-slate-50 py-24">
  <div className="mx-auto max-w-7xl px-6 lg:px-8">
   <div className="mx-auto max-w-4xl text-center"><div className="text-xs font-black uppercase tracking-[.22em] text-red-500">{h.eyebrow}</div><h2 className="mt-4 text-4xl font-black tracking-tight md:text-5xl">{h.title}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{h.intro}</p></div>
   <div className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.map((card,i)=><article key={card.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-12 min-w-12 items-center justify-center rounded-2xl bg-slate-950 px-2 text-xs font-black text-white">{card.icon}</div><div><div className="text-[10px] font-black uppercase tracking-widest text-red-500">0{i+1}</div><h3 className="mt-1 text-xl font-black">{card.title}</h3></div></div><div className="mt-5 rounded-xl bg-slate-950 p-3 font-mono text-sm font-bold text-emerald-300">{card.serial}</div><p className="mt-4 leading-7 text-slate-700">{card.text}</p><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm font-semibold leading-6 text-slate-600">{card.hint}</p></article>)}</div>
   <div className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-semibold leading-6 text-amber-950">⚠️ {h.warning}</div><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm font-semibold leading-6 text-blue-950">🔧 {h.safety}</div></div>
   <div className="mt-10 text-center"><a href="#request-form" className="inline-flex rounded-xl bg-red-500 px-7 py-4 font-black text-white transition hover:bg-red-400">{h.cta}</a></div>
  </div>
 </section>;
}
