"use client";

import { useState } from "react";
import Image from "next/image";
import CheckoutRequestForm from "./CheckoutRequestForm";
import { languageOptions, type Language } from "./languages";

const brands = [
  { name: "HONDA", logo: "/brands/honda.svg" },
  { name: "ACURA", logo: "/brands/acura.svg" },
  { name: "TOYOTA", logo: "/brands/toyota.svg" },
  { name: "NISSAN", logo: "/brands/nissan.svg" },
  { name: "FORD", logo: "/brands/ford.svg" },
  { name: "CHEVROLET", logo: "/brands/chevrolet.svg" },
  { name: "VOLKSWAGEN", logo: "/brands/volkswagen.svg" },
  { name: "BMW", logo: "/brands/bmw.svg" },
  { name: "MERCEDES-BENZ", logo: "/brands/mercedes-benz.svg" },
  { name: "AUDI", logo: "/brands/audi.svg" },
];

type PageCopy = {
  navHome:string; navRequest:string; navSerial:string; navFaq:string; navContact:string;
  hero1:string; hero2:string; heroText:string; safe:string; fast:string; support:string; request:string; unknown:string;
  brandsTitle:string; brandsSub:string; more:string; disclaimer:string;
  serialEyebrow:string; serialTitle:string; serialText:string; method1:string; method2:string; serialCta:string;
  works:string; worksSub:string; step1:string; step1Text:string; step2:string; step2Text:string; step3:string; step3Text:string;
  faqTitle:string; faqSub:string; faq1q:string; faq1a:string; faq2q:string; faq2a:string; faq3q:string; faq3a:string;
  help:string; helpSub:string; requestNow:string; requestSub:string; goForm:string; secure:string; footer:string; tagline:string;
};

const copy: Record<Language, PageCopy> = {
  en:{navHome:"Home",navRequest:"Request Code",navSerial:"Find Serial Number",navFaq:"FAQ",navContact:"Contact",hero1:"Get Your Car",hero2:"Stereo Code",heroText:"Security codes for factory car radios and stereos. Fast, secure and easy.",safe:"Secure",fast:"Fast delivery",support:"Expert support",request:"Request My Code →",unknown:"I don't know which serial number to enter",brandsTitle:"Compatible with Major Vehicle Brands",brandsSub:"We work with factory radios from many manufacturers.",more:"and more…",disclaimer:"Brand names and logos belong to their respective owners and are shown only to indicate compatibility.",serialEyebrow:"Before you order",serialTitle:"Find the correct stereo serial number",serialText:"The serial identifies the radio itself. It is not the same as your vehicle VIN. Older Honda / Acura units may show it with 1 + 6 + PWR/VOL; other radios may have it on a physical label.",method1:"Honda / Acura: hold 1 + 6, then press PWR/VOL on compatible older radios.",method2:"Physical label: check the top, side or rear of the stereo chassis if the serial is not shown on screen.",serialCta:"See the complete serial-number guide →",works:"How It Works",worksSub:"Three simple steps.",step1:"Enter the stereo serial",step1Text:"Provide the serial number printed or displayed by your radio.",step2:"Pay securely",step2Text:"Complete the $23.99 USD payment through PayPal.",step3:"Receive your code",step3Text:"We send the code to the email you provide, with optional priority SMS.",faqTitle:"Frequently Asked Questions",faqSub:"Quick answers before ordering.",faq1q:"Is the VIN the same as the stereo serial?",faq1a:"No. The VIN identifies the vehicle; the serial identifies the radio unit.",faq2q:"What if I cannot find the serial?",faq2a:"Use the detailed guide below. If the unit must be removed, consider using an installer or technician.",faq3q:"How will I receive my code?",faq3a:"By email. You can also add priority SMS for an additional fee.",help:"Need help?",helpSub:"Use the serial-number guide before ordering so you submit the correct information.",requestNow:"Ready to request your code?",requestSub:"You only need the stereo serial number and an email address.",goForm:"Go to Request Form →",secure:"Your payment is processed securely through PayPal.",footer:"© 2026 Auto Stereo Codes. All rights reserved.",tagline:"Fast • Secure • Simple"},
  es:{navHome:"Inicio",navRequest:"Solicitar Código",navSerial:"Encontrar Serie",navFaq:"Preguntas",navContact:"Contacto",hero1:"Obtén el Código",hero2:"de Tu Estéreo",heroText:"Códigos de seguridad para radios y estéreos originales. Rápido, seguro y sencillo.",safe:"Seguro",fast:"Entrega rápida",support:"Soporte experto",request:"Solicitar Mi Código →",unknown:"No sé qué número de serie poner",brandsTitle:"Compatible con las Principales Marcas",brandsSub:"Trabajamos con radios originales de muchos fabricantes.",more:"y muchas más…",disclaimer:"Los nombres y logotipos pertenecen a sus respectivos propietarios y se muestran únicamente para indicar compatibilidad.",serialEyebrow:"Antes de solicitar",serialTitle:"Encuentra la serie correcta de tu estéreo",serialText:"La serie identifica al radio. No es lo mismo que el VIN del vehículo. En muchos Honda / Acura antiguos puede aparecer con 1 + 6 + PWR/VOL; en otros radios puede estar en una etiqueta física.",method1:"Honda / Acura: mantén 1 + 6 y presiona PWR/VOL en radios antiguos compatibles.",method2:"Etiqueta física: revisa la parte superior, lateral o trasera del estéreo si la serie no aparece en pantalla.",serialCta:"Ver la guía completa para encontrar la serie →",works:"Cómo Funciona",worksSub:"Solo tres pasos.",step1:"Introduce la serie del estéreo",step1Text:"Ingresa la serie impresa o mostrada por tu radio.",step2:"Paga de forma segura",step2Text:"Completa el pago de $23.99 USD mediante PayPal.",step3:"Recibe tu código",step3Text:"Enviamos el código al correo que indiques, con SMS prioritario opcional.",faqTitle:"Preguntas Frecuentes",faqSub:"Respuestas rápidas antes de solicitar.",faq1q:"¿El VIN es lo mismo que la serie del estéreo?",faq1a:"No. El VIN identifica el vehículo; la serie identifica al radio.",faq2q:"¿Qué hago si no encuentro la serie?",faq2a:"Usa la guía detallada de abajo. Si hay que desmontar el radio, considera acudir con un instalador o técnico.",faq3q:"¿Cómo recibiré mi código?",faq3a:"Por correo electrónico. También puedes agregar SMS prioritario por un costo adicional.",help:"¿Necesitas ayuda?",helpSub:"Consulta primero la guía de la serie para enviar el dato correcto.",requestNow:"¿Listo para solicitar tu código?",requestSub:"Solo necesitas la serie del estéreo y un correo electrónico.",goForm:"Ir al Formulario →",secure:"Tu pago se procesa de forma segura mediante PayPal.",footer:"© 2026 Auto Stereo Codes. Todos los derechos reservados.",tagline:"Rápido • Seguro • Sencillo"},
  pt:{navHome:"Início",navRequest:"Solicitar Código",navSerial:"Encontrar Série",navFaq:"Perguntas",navContact:"Contato",hero1:"Obtenha o Código",hero2:"do Seu Rádio",heroText:"Códigos de segurança para rádios originais. Rápido, seguro e simples.",safe:"Seguro",fast:"Entrega rápida",support:"Suporte especializado",request:"Solicitar Meu Código →",unknown:"Não sei qual número de série informar",brandsTitle:"Compatível com as Principais Marcas",brandsSub:"Trabalhamos com rádios originais de muitos fabricantes.",more:"e muitas outras…",disclaimer:"Marcas e logotipos pertencem aos seus respectivos proprietários e são exibidos apenas para indicar compatibilidade.",serialEyebrow:"Antes de solicitar",serialTitle:"Encontre o número de série correto do rádio",serialText:"O número de série identifica o rádio e não é o VIN do veículo. Em muitos Honda / Acura antigos ele aparece com 1 + 6 + PWR/VOL; em outros aparelhos pode estar em uma etiqueta física.",method1:"Honda / Acura: segure 1 + 6 e pressione PWR/VOL em rádios antigos compatíveis.",method2:"Etiqueta física: verifique a parte superior, lateral ou traseira do aparelho se a série não aparecer na tela.",serialCta:"Ver guia completo do número de série →",works:"Como Funciona",worksSub:"Apenas três passos.",step1:"Digite o número de série",step1Text:"Informe o número exibido ou impresso no rádio.",step2:"Pague com segurança",step2Text:"Conclua o pagamento de US$23,99 via PayPal.",step3:"Receba seu código",step3Text:"Enviamos o código por e-mail, com SMS prioritário opcional.",faqTitle:"Perguntas Frequentes",faqSub:"Respostas rápidas antes do pedido.",faq1q:"O VIN é igual ao número de série do rádio?",faq1a:"Não. O VIN identifica o veículo; o número de série identifica o rádio.",faq2q:"E se eu não encontrar o número de série?",faq2a:"Use o guia detalhado abaixo. Se for necessário remover o rádio, procure um instalador ou técnico.",faq3q:"Como receberei meu código?",faq3a:"Por e-mail. Você também pode adicionar SMS prioritário por uma taxa extra.",help:"Precisa de ajuda?",helpSub:"Consulte o guia do número de série antes de fazer o pedido.",requestNow:"Pronto para solicitar seu código?",requestSub:"Você só precisa do número de série e de um e-mail.",goForm:"Ir para o Formulário →",secure:"Seu pagamento é processado com segurança pelo PayPal.",footer:"© 2026 Auto Stereo Codes. Todos os direitos reservados.",tagline:"Rápido • Seguro • Simples"},
  fr:{navHome:"Accueil",navRequest:"Demander le Code",navSerial:"Trouver le Numéro",navFaq:"FAQ",navContact:"Contact",hero1:"Obtenez le Code",hero2:"de Votre Autoradio",heroText:"Codes de sécurité pour autoradios d’origine. Rapide, sécurisé et simple.",safe:"Sécurisé",fast:"Livraison rapide",support:"Assistance experte",request:"Demander Mon Code →",unknown:"Je ne sais pas quel numéro de série saisir",brandsTitle:"Compatible avec les Grandes Marques",brandsSub:"Nous travaillons avec les autoradios d’origine de nombreux constructeurs.",more:"et bien d’autres…",disclaimer:"Les marques et logos appartiennent à leurs propriétaires respectifs et sont affichés uniquement pour indiquer la compatibilité.",serialEyebrow:"Avant de commander",serialTitle:"Trouvez le bon numéro de série",serialText:"Le numéro de série identifie l’autoradio et n’est pas le VIN du véhicule. Sur de nombreux anciens Honda / Acura, utilisez 1 + 6 + PWR/VOL; sinon cherchez l’étiquette physique.",method1:"Honda / Acura : maintenez 1 + 6 puis appuyez sur PWR/VOL sur les anciens modèles compatibles.",method2:"Étiquette physique : vérifiez le dessus, le côté ou l’arrière de l’autoradio si le numéro n’apparaît pas à l’écran.",serialCta:"Voir le guide complet du numéro de série →",works:"Comment Ça Marche",worksSub:"Trois étapes simples.",step1:"Saisissez le numéro de série",step1Text:"Indiquez le numéro affiché ou imprimé sur l’autoradio.",step2:"Payez en toute sécurité",step2Text:"Effectuez le paiement de 23,99 $US via PayPal.",step3:"Recevez votre code",step3Text:"Nous envoyons le code par e-mail, avec SMS prioritaire en option.",faqTitle:"Questions Fréquentes",faqSub:"Réponses rapides avant de commander.",faq1q:"Le VIN est-il le numéro de série de l’autoradio ?",faq1a:"Non. Le VIN identifie le véhicule; le numéro de série identifie l’autoradio.",faq2q:"Que faire si je ne trouve pas le numéro de série ?",faq2a:"Utilisez le guide détaillé ci-dessous. Si l’autoradio doit être retiré, demandez l’aide d’un technicien.",faq3q:"Comment recevrai-je mon code ?",faq3a:"Par e-mail. Vous pouvez aussi ajouter un SMS prioritaire moyennant un supplément.",help:"Besoin d’aide ?",helpSub:"Consultez d’abord le guide du numéro de série pour envoyer la bonne information.",requestNow:"Prêt à demander votre code ?",requestSub:"Il vous suffit du numéro de série et d’une adresse e-mail.",goForm:"Aller au Formulaire →",secure:"Votre paiement est traité en toute sécurité par PayPal.",footer:"© 2026 Auto Stereo Codes. Tous droits réservés.",tagline:"Rapide • Sécurisé • Simple"},
  de:{navHome:"Start",navRequest:"Code Anfordern",navSerial:"Seriennummer Finden",navFaq:"FAQ",navContact:"Kontakt",hero1:"Hol Dir den Code",hero2:"für Dein Autoradio",heroText:"Sicherheitscodes für Original-Autoradios. Schnell, sicher und einfach.",safe:"Sicher",fast:"Schnelle Lieferung",support:"Experten-Support",request:"Meinen Code Anfordern →",unknown:"Ich weiß nicht, welche Seriennummer ich eingeben soll",brandsTitle:"Kompatibel mit Wichtigen Automarken",brandsSub:"Wir arbeiten mit Originalradios vieler Hersteller.",more:"und viele mehr…",disclaimer:"Markennamen und Logos gehören ihren jeweiligen Eigentümern und dienen nur zur Anzeige der Kompatibilität.",serialEyebrow:"Vor der Bestellung",serialTitle:"Finde die richtige Seriennummer",serialText:"Die Seriennummer gehört zum Radio und ist nicht die Fahrzeug-VIN. Bei vielen älteren Honda / Acura Geräten funktioniert 1 + 6 + PWR/VOL; sonst befindet sie sich oft auf einem Aufkleber.",method1:"Honda / Acura: 1 + 6 gedrückt halten und bei kompatiblen älteren Radios PWR/VOL drücken.",method2:"Aufkleber: Oberseite, Seite oder Rückseite des Radios prüfen, wenn die Nummer nicht im Display erscheint.",serialCta:"Vollständige Seriennummer-Anleitung anzeigen →",works:"So Funktioniert Es",worksSub:"Nur drei Schritte.",step1:"Seriennummer eingeben",step1Text:"Gib die angezeigte oder aufgedruckte Seriennummer des Radios ein.",step2:"Sicher bezahlen",step2Text:"Bezahle 23,99 US$ sicher über PayPal.",step3:"Code erhalten",step3Text:"Wir senden den Code per E-Mail; Prioritäts-SMS ist optional.",faqTitle:"Häufige Fragen",faqSub:"Kurze Antworten vor der Bestellung.",faq1q:"Ist die VIN die Seriennummer des Radios?",faq1a:"Nein. Die VIN identifiziert das Fahrzeug; die Seriennummer identifiziert das Radio.",faq2q:"Was tun, wenn ich die Seriennummer nicht finde?",faq2a:"Nutze die ausführliche Anleitung unten. Wenn das Radio ausgebaut werden muss, wende dich an einen Techniker.",faq3q:"Wie erhalte ich meinen Code?",faq3a:"Per E-Mail. Optional kannst du gegen Aufpreis eine Prioritäts-SMS hinzufügen.",help:"Brauchst du Hilfe?",helpSub:"Nutze zuerst die Seriennummer-Anleitung, damit du die richtige Information sendest.",requestNow:"Bereit für deinen Code?",requestSub:"Du brauchst nur die Seriennummer und eine E-Mail-Adresse.",goForm:"Zum Formular →",secure:"Die Zahlung wird sicher über PayPal verarbeitet.",footer:"© 2026 Auto Stereo Codes. Alle Rechte vorbehalten.",tagline:"Schnell • Sicher • Einfach"},
  it:{navHome:"Home",navRequest:"Richiedi Codice",navSerial:"Trova Numero di Serie",navFaq:"FAQ",navContact:"Contatti",hero1:"Ottieni il Codice",hero2:"della Tua Autoradio",heroText:"Codici di sicurezza per autoradio originali. Rapido, sicuro e semplice.",safe:"Sicuro",fast:"Consegna rapida",support:"Supporto esperto",request:"Richiedi il Mio Codice →",unknown:"Non so quale numero di serie inserire",brandsTitle:"Compatibile con le Principali Marche",brandsSub:"Lavoriamo con autoradio originali di molti produttori.",more:"e molte altre…",disclaimer:"Marchi e loghi appartengono ai rispettivi proprietari e sono mostrati solo per indicare la compatibilità.",serialEyebrow:"Prima di ordinare",serialTitle:"Trova il numero di serie corretto",serialText:"Il numero di serie identifica l’autoradio e non è il VIN del veicolo. Su molti vecchi Honda / Acura funziona 1 + 6 + PWR/VOL; altrimenti cerca l’etichetta fisica.",method1:"Honda / Acura: tieni premuti 1 + 6 e premi PWR/VOL sulle unità più vecchie compatibili.",method2:"Etichetta fisica: controlla la parte superiore, laterale o posteriore se il numero non appare sul display.",serialCta:"Vedi la guida completa al numero di serie →",works:"Come Funziona",worksSub:"Tre semplici passaggi.",step1:"Inserisci il numero di serie",step1Text:"Inserisci il numero visualizzato o stampato sull’autoradio.",step2:"Paga in sicurezza",step2Text:"Completa il pagamento di 23,99 USD tramite PayPal.",step3:"Ricevi il codice",step3Text:"Invieremo il codice via email, con SMS prioritario opzionale.",faqTitle:"Domande Frequenti",faqSub:"Risposte rapide prima dell’ordine.",faq1q:"Il VIN è uguale al numero di serie?",faq1a:"No. Il VIN identifica il veicolo; il numero di serie identifica l’autoradio.",faq2q:"Cosa faccio se non trovo il numero di serie?",faq2a:"Usa la guida dettagliata qui sotto. Se bisogna rimuovere l’autoradio, chiedi aiuto a un tecnico.",faq3q:"Come riceverò il codice?",faq3a:"Via email. Puoi anche aggiungere un SMS prioritario con un costo extra.",help:"Hai bisogno di aiuto?",helpSub:"Consulta prima la guida del numero di serie per inviare il dato corretto.",requestNow:"Pronto a richiedere il codice?",requestSub:"Ti servono solo il numero di serie e un indirizzo email.",goForm:"Vai al Modulo →",secure:"Il pagamento viene elaborato in modo sicuro da PayPal.",footer:"© 2026 Auto Stereo Codes. Tutti i diritti riservati.",tagline:"Rapido • Sicuro • Semplice"},
};

export default function Home() {
  const [language, setLanguage] = useState<Language>("en");
  const [showLanguages, setShowLanguages] = useState(false);
  const t = copy[language];
  const selectedLanguage = languageOptions.find(item=>item.code===language)!;
  const steps = [
    { number:"1", image:"/step-details.svg", title:t.step1, text:t.step1Text },
    { number:"2", image:"/step-payment.svg", title:t.step2, text:t.step2Text },
    { number:"3", image:"/step-code.svg", title:t.step3, text:t.step3Text },
  ];

  return <main className="min-h-screen bg-white text-slate-900">
    <header className="absolute left-0 top-0 z-30 w-full">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-5 lg:px-10">
        <div className="flex items-center gap-3"><Image src="/brand-mark.svg" alt="" width={46} height={46} className="h-11 w-11"/><div><div className="text-xl font-black tracking-tight text-white">AUTO <span className="text-blue-400">STEREO</span> CODES</div><div className="text-[9px] tracking-[0.28em] text-slate-400">UNLOCK YOUR CAR STEREO</div></div></div>
        <nav className="hidden items-center gap-6 xl:flex"><a href="#" className="text-sm text-white hover:text-blue-400">{t.navHome}</a><a href="#request-form" className="text-sm text-white hover:text-blue-400">{t.navRequest}</a><a href="#serial" className="text-sm text-white hover:text-blue-400">{t.navSerial}</a><a href="#faq" className="text-sm text-white hover:text-blue-400">{t.navFaq}</a><a href="#contact" className="text-sm text-white hover:text-blue-400">{t.navContact}</a></nav>
        <div className="relative"><button onClick={()=>setShowLanguages(v=>!v)} className="flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-2 text-xs font-bold text-white backdrop-blur"><span>{selectedLanguage.flag}</span><span className="hidden sm:inline">{selectedLanguage.label}</span><span>⌄</span></button>{showLanguages&&<div className="absolute right-0 mt-2 w-56 overflow-hidden rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl">{languageOptions.map(item=><button key={item.code} onClick={()=>{setLanguage(item.code);setShowLanguages(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${language===item.code?"bg-blue-50 font-black text-blue-700":"text-slate-700 hover:bg-slate-50"}`}><span>{item.flag}</span><span>{item.label}</span>{language===item.code&&<span className="ml-auto">✓</span>}</button>)}</div>}</div>
      </div>
    </header>

    <section className="relative overflow-hidden bg-slate-950"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_40%,rgba(37,99,235,0.25),transparent_35%)]"/><div className="relative mx-auto grid min-h-[720px] max-w-7xl items-center gap-12 px-6 pb-20 pt-36 lg:grid-cols-2 lg:px-10"><div><div className="mb-5 inline-flex rounded-full border border-blue-400/20 bg-blue-500/10 px-4 py-2 text-xs font-semibold uppercase tracking-wider text-blue-300">Car Radio Code Service</div><h1 className="max-w-2xl text-5xl font-black leading-[1.05] tracking-tight text-white md:text-7xl">{t.hero1}<br/><span className="text-blue-400">{t.hero2}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">{t.heroText}</p><div className="mt-8 flex flex-wrap gap-6"><span className="text-sm font-semibold text-white">🛡️ {t.safe}</span><span className="text-sm font-semibold text-white">⚡ {t.fast}</span><span className="text-sm font-semibold text-white">🎧 {t.support}</span></div><div className="mt-10 flex flex-wrap gap-3"><a href="#request-form" className="inline-flex rounded-xl bg-blue-600 px-7 py-4 font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-500">{t.request}</a><a href="#serial-help" className="inline-flex rounded-xl border border-white/20 bg-white/5 px-7 py-4 font-bold text-white hover:bg-white/10">? {t.unknown}</a></div></div><div className="relative flex items-center justify-center"><div className="absolute h-80 w-80 rounded-full bg-blue-600/20 blur-3xl"/><Image src="/stereo-hero-v1.png" alt="Car stereo" width={1536} height={1024} priority className="relative h-auto w-full rounded-3xl shadow-2xl"/></div></div></section>

    <section className="border-b border-slate-200 bg-white py-14"><div className="mx-auto max-w-7xl px-6 lg:px-10"><h2 className="text-center text-2xl font-black">{t.brandsTitle}</h2><p className="mt-2 text-center text-slate-500">{t.brandsSub}</p><div className="mt-9 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{brands.map(brand=><div key={brand.name} className="flex min-h-28 flex-col items-center justify-center rounded-2xl border border-slate-200 bg-slate-50 px-4 py-5"><Image src={brand.logo} alt={`${brand.name} logo`} width={96} height={52} unoptimized className="h-11 w-auto max-w-24 object-contain opacity-75"/><span className="mt-3 text-xs font-black text-slate-600">{brand.name}</span></div>)}</div><div className="mt-5 text-center text-sm font-semibold text-blue-600">{t.more}</div><p className="mx-auto mt-4 max-w-3xl text-center text-[11px] leading-5 text-slate-400">{t.disclaimer}</p></div></section>

    <section id="serial" className="bg-white py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 lg:grid-cols-2 lg:px-10"><div><Image src="/serial-guide.svg" alt="Stereo serial number guide" width={1200} height={800} className="h-auto w-full rounded-3xl shadow-xl"/></div><div><div className="text-sm font-black uppercase tracking-[0.22em] text-blue-600">{t.serialEyebrow}</div><h2 className="mt-4 text-4xl font-black md:text-5xl">{t.serialTitle}</h2><p className="mt-6 text-lg leading-8 text-slate-600">{t.serialText}</p><div className="mt-7 space-y-4"><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 font-semibold text-slate-700">1 + 6 + PWR/VOL · {t.method1}</div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5 font-semibold text-slate-700">🏷️ {t.method2}</div></div><a href="#serial-help" className="mt-7 inline-flex rounded-xl bg-slate-950 px-6 py-3.5 font-bold text-white hover:bg-blue-600">{t.serialCta}</a></div></div></section>

    <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="text-center"><h2 className="text-4xl font-black">{t.works}</h2><p className="mt-3 text-slate-500">{t.worksSub}</p></div><div className="mt-14 grid gap-8 md:grid-cols-3">{steps.map(step=><div key={step.number} className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><div className="p-4 pb-0"><Image src={step.image} alt="" width={800} height={520} className="h-auto w-full rounded-2xl"/></div><div className="p-8 pt-6 text-center"><div className="text-xs font-black uppercase tracking-widest text-blue-600">{step.number}</div><h3 className="mt-3 text-xl font-bold">{step.title}</h3><p className="mt-3 leading-7 text-slate-500">{step.text}</p></div></div>)}</div></div></section>

    <section id="faq" className="bg-white py-24"><div className="mx-auto max-w-5xl px-6 lg:px-10"><div className="text-center"><h2 className="text-4xl font-black">{t.faqTitle}</h2><p className="mt-3 text-slate-500">{t.faqSub}</p></div><div className="mt-12 grid gap-5">{[[t.faq1q,t.faq1a],[t.faq2q,t.faq2a],[t.faq3q,t.faq3a]].map(([q,a])=><div key={q} className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><h3 className="text-lg font-bold">{q}</h3><p className="mt-2 leading-7 text-slate-600">{a}</p></div>)}</div></div></section>

    <section id="contact" className="bg-slate-950 py-24"><div className="mx-auto grid max-w-7xl gap-8 px-6 lg:grid-cols-2 lg:px-10"><div className="rounded-3xl border border-white/10 bg-slate-900 p-8 md:p-12"><div className="text-sm font-bold uppercase tracking-[0.2em] text-blue-400">Support</div><h2 className="mt-4 text-4xl font-black text-white">{t.help}</h2><p className="mt-4 text-lg leading-8 text-slate-400">{t.helpSub}</p><a href="#serial-help" className="mt-8 inline-flex rounded-xl border border-blue-400/30 bg-blue-500/10 px-6 py-3 font-bold text-blue-200">{t.unknown} →</a></div><div className="flex flex-col justify-center rounded-3xl bg-white p-8 md:p-12"><h2 className="text-4xl font-black">{t.requestNow}</h2><p className="mt-4 text-lg leading-8 text-slate-500">{t.requestSub}</p><a href="#request-form" className="mt-8 inline-flex w-fit rounded-xl bg-blue-600 px-7 py-4 font-bold text-white hover:bg-blue-500">{t.goForm}</a><div className="mt-6 text-sm text-slate-500">🔒 {t.secure}</div></div></div></section>

    <CheckoutRequestForm language={language}/>

    <footer className="border-t border-slate-800 bg-slate-950 py-10"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-6 md:flex-row md:items-center md:justify-between lg:px-10"><div className="flex items-center gap-3"><Image src="/brand-mark.svg" alt="" width={38} height={38}/><div><div className="text-lg font-black text-white">AUTO <span className="text-blue-400">STEREO</span> CODES</div><div className="mt-1 text-[9px] tracking-[0.25em] text-slate-500">UNLOCK YOUR CAR STEREO</div></div></div><div className="text-sm text-slate-500">{t.footer}</div><div className="text-sm font-semibold text-slate-400">{t.tagline}</div></div></footer>
  </main>;
}
