"use client";

import Link from "next/link";
import { useState } from "react";
import CheckoutRequestForm from "./CheckoutRequestForm";
import UniversalSerialFinder from "./UniversalSerialFinder";
import { languageOptions, type Language } from "./languages";

const HERO_IMAGE = "https://images.unsplash.com/photo-1738181957156-1379f9098688?auto=format&fit=crop&fm=jpg&q=82&w=2400";
const tickerBrands = ["HONDA","ACURA","FORD","VOLKSWAGEN","AUDI","SEAT","ŠKODA","NISSAN","RENAULT","DACIA","TOYOTA","FIAT","ALFA ROMEO","PEUGEOT","CITROËN","MERCEDES-BENZ","BMW","JEEP","CHRYSLER","DODGE","LAND ROVER","JAGUAR","PORSCHE","SUZUKI","IVECO"];

const strings: Record<Language, {all:string; how:string; serial:string; help:string; order:string; badge:string; heroA:string; heroB:string; heroText:string; guide:string; ticker:string; allTitle:string; allText:string; explore:string; stepsTitle:string; step1:string; step1t:string; step2:string; step2t:string; step3:string; step3t:string; whyTitle:string; whyText:string; faq:string; q1:string; a1:string; q2:string; a2:string; q3:string; a3:string}> = {
  es:{all:"Todas las marcas",how:"Cómo funciona",serial:"Encontrar serie",help:"Centro de ayuda",order:"Solicitar código",badge:"IDENTIFICA · CONFIRMA · SOLICITA",heroA:"Tu radio, identificado",heroB:"antes de pagar.",heroText:"Escribe la serie de tu estéreo. Nuestro sistema compara familias conocidas y te muestra una o varias opciones cuando el mismo fabricante de radio aparece en diferentes marcas de carro.",guide:"No sé cuál es mi número de serie",ticker:"Marcas y fabricantes compatibles",allTitle:"Una guía independiente para cada marca",allText:"Ya no tienes que buscar toda la información en una sola página. Entra a Todas las marcas, elige Honda, Ford, Jeep, Volkswagen, Nissan u otra familia y abre una pantalla con instrucciones específicas para ese tipo de radio.",explore:"Explorar las 36 guías →",stepsTitle:"Del número de serie al pedido, sin adivinar",step1:"1. Encuentra la serie",step1t:"Consulta la guía de tu marca y escoge el procedimiento que coincide con la pantalla o etiqueta de tu estéreo.",step2:"2. Identifica la familia",step2t:"El buscador reconoce prefijos como VWZ, AUZ, V-series, BP, A2C, BE, T-series y otros formatos conocidos.",step3:"3. Solicita el código",step3t:"Confirma la opción correcta, escribe tu correo y completa el pago seguro. Solo entonces se crea tu folio.",whyTitle:"Hecho para radios de muchas marcas",whyText:"Un mismo fabricante —Blaupunkt, Bosch, Continental, Clarion, Visteon, Becker o Alpine— puede aparecer en diferentes vehículos. Por eso Auto Stereo Codes prioriza identificar la unidad real en vez de asumir que la marca del carro basta.",faq:"Preguntas frecuentes",q1:"¿La serie siempre identifica el carro exacto?",a1:"No. Algunas familias de radio se instalaron en varias marcas. Cuando hay más de una posibilidad, el sitio muestra las opciones para que confirmes la correcta.",q2:"¿Todas las radios muestran la serie en pantalla?",a2:"No. Algunas la muestran mediante un menú o botones; muchas otras requieren leer una etiqueta en la carcasa. Las guías por marca explican cuál método corresponde.",q3:"¿Existe un generador universal de códigos?",a3:"No. Algunas unidades antiguas permiten calcular el código a partir de la serie, mientras otras dependen de bases de datos o emparejamiento con el vehículo."},
  en:{all:"All radio codes",how:"How it works",serial:"Find serial",help:"Help centre",order:"Request code",badge:"IDENTIFY · CONFIRM · ORDER",heroA:"Identify your radio",heroB:"before you pay.",heroText:"Enter the stereo serial. Our matcher compares known radio families and shows one or several possibilities when the same radio maker was fitted to different vehicle brands.",guide:"I don't know my serial number",ticker:"Supported makes and radio families",allTitle:"A separate guide for every radio family",allText:"Open All radio codes, choose Honda, Ford, Jeep, Volkswagen, Nissan or another family, and see a dedicated screen with the serial-finding methods for that unit.",explore:"Explore all 36 guides →",stepsTitle:"From serial number to order without guessing",step1:"1. Find the serial",step1t:"Open the guide for your make and choose the method that matches your radio screen or label.",step2:"2. Identify the family",step2t:"The matcher recognizes prefixes such as VWZ, AUZ, V-series, BP, A2C, BE and T-series.",step3:"3. Request the code",step3t:"Confirm the correct option, enter your email and complete secure payment. Your reference is created only after payment.",whyTitle:"Built for many radio manufacturers",whyText:"Blaupunkt, Bosch, Continental, Clarion, Visteon, Becker and Alpine supplied radios to multiple vehicle brands, so identifying the actual unit is more reliable than relying on the badge alone.",faq:"Frequently asked questions",q1:"Does the serial always identify the exact car?",a1:"No. Some radio families were installed in several brands. When there are multiple possibilities, the site shows the options for confirmation.",q2:"Do all radios show the serial on screen?",a2:"No. Some use a menu or button sequence; many require reading the casing label. The brand guides explain the appropriate method.",q3:"Is there a universal radio-code generator?",a3:"No. Some older units can be calculated from a serial while others depend on databases or vehicle pairing."},
  pt:{all:"Todos os códigos",how:"Como funciona",serial:"Encontrar série",help:"Central de ajuda",order:"Solicitar código",badge:"IDENTIFICAR · CONFIRMAR · SOLICITAR",heroA:"Identifique seu rádio",heroB:"antes de pagar.",heroText:"Digite o serial do rádio. O sistema compara famílias conhecidas e mostra as opções prováveis.",guide:"Não sei qual é meu serial",ticker:"Marcas e famílias compatíveis",allTitle:"Uma guia separada para cada marca",allText:"Abra Todos os códigos, escolha a marca e veja instruções específicas para localizar o serial.",explore:"Ver as 36 guias →",stepsTitle:"Do serial ao pedido sem adivinhar",step1:"1. Encontre o serial",step1t:"Use a guia da sua marca.",step2:"2. Identifique a família",step2t:"O sistema compara prefixos e formatos conhecidos.",step3:"3. Solicite o código",step3t:"Confirme, informe o e-mail e pague com segurança.",whyTitle:"Feito para muitas marcas",whyText:"O mesmo fabricante de rádio pode fornecer unidades para várias marcas de veículos.",faq:"Perguntas frequentes",q1:"O serial sempre identifica o carro?",a1:"Não. Algumas famílias aparecem em várias marcas.",q2:"Todos os rádios mostram o serial na tela?",a2:"Não. Muitos exigem a etiqueta física.",q3:"Existe um gerador universal?",a3:"Não. O método depende da família do rádio."},
  fr:{all:"Tous les codes",how:"Comment ça marche",serial:"Trouver le numéro",help:"Centre d’aide",order:"Demander le code",badge:"IDENTIFIER · CONFIRMER · COMMANDER",heroA:"Identifiez l’autoradio",heroB:"avant de payer.",heroText:"Saisissez le numéro de série. Le système compare les familles connues et affiche les options probables.",guide:"Je ne connais pas mon numéro",ticker:"Marques et familles compatibles",allTitle:"Un guide séparé pour chaque marque",allText:"Ouvrez Tous les codes, choisissez la marque et consultez les méthodes adaptées.",explore:"Voir les 36 guides →",stepsTitle:"Du numéro de série à la commande",step1:"1. Trouvez le numéro",step1t:"Utilisez le guide de votre marque.",step2:"2. Identifiez la famille",step2t:"Le système compare les préfixes connus.",step3:"3. Demandez le code",step3t:"Confirmez, saisissez votre e-mail et payez en sécurité.",whyTitle:"Conçu pour de nombreuses marques",whyText:"Un même fabricant d’autoradio équipe plusieurs marques de véhicules.",faq:"Questions fréquentes",q1:"Le numéro identifie-t-il toujours la voiture ?",a1:"Non. Certaines familles sont partagées.",q2:"Tous les autoradios affichent-ils le numéro ?",a2:"Non. Beaucoup nécessitent de lire l’étiquette.",q3:"Existe-t-il un générateur universel ?",a3:"Non. La méthode dépend de la famille de l’autoradio."},
  de:{all:"Alle Radiocodes",how:"So funktioniert es",serial:"Seriennummer finden",help:"Hilfe-Center",order:"Code anfordern",badge:"IDENTIFIZIEREN · BESTÄTIGEN · BESTELLEN",heroA:"Radio identifizieren",heroB:"bevor du bezahlst.",heroText:"Seriennummer eingeben. Das System vergleicht bekannte Radiofamilien und zeigt passende Optionen.",guide:"Seriennummer unbekannt",ticker:"Unterstützte Marken und Radiofamilien",allTitle:"Eigene Anleitung für jede Marke",allText:"Öffne Alle Radiocodes, wähle die Marke und erhalte passende Anleitungen.",explore:"Alle 36 Anleitungen →",stepsTitle:"Von der Seriennummer zur Bestellung",step1:"1. Seriennummer finden",step1t:"Nutze die Anleitung deiner Marke.",step2:"2. Radiofamilie erkennen",step2t:"Bekannte Präfixe und Formate werden verglichen.",step3:"3. Code anfordern",step3t:"Bestätigen, E-Mail eingeben und sicher bezahlen.",whyTitle:"Für viele Marken gebaut",whyText:"Ein Radiohersteller kann mehrere Fahrzeugmarken beliefern.",faq:"Häufige Fragen",q1:"Identifiziert die Seriennummer immer das Auto?",a1:"Nein. Manche Radiofamilien werden von mehreren Marken genutzt.",q2:"Zeigen alle Radios die Seriennummer im Display?",a2:"Nein. Oft muss das Etikett gelesen werden.",q3:"Gibt es einen Universal-Generator?",a3:"Nein. Das Verfahren hängt von der Radiofamilie ab."},
  it:{all:"Tutti i codici",how:"Come funziona",serial:"Trova seriale",help:"Centro assistenza",order:"Richiedi codice",badge:"IDENTIFICA · CONFERMA · ORDINA",heroA:"Identifica l’autoradio",heroB:"prima di pagare.",heroText:"Inserisci il seriale. Il sistema confronta famiglie note e mostra le opzioni probabili.",guide:"Non conosco il seriale",ticker:"Marche e famiglie supportate",allTitle:"Una guida separata per ogni marca",allText:"Apri Tutti i codici, scegli la marca e visualizza i metodi specifici.",explore:"Vedi tutte le 36 guide →",stepsTitle:"Dal seriale all’ordine",step1:"1. Trova il seriale",step1t:"Usa la guida della tua marca.",step2:"2. Identifica la famiglia",step2t:"Il sistema confronta prefissi e formati noti.",step3:"3. Richiedi il codice",step3t:"Conferma, inserisci l’email e paga in sicurezza.",whyTitle:"Pensato per molte marche",whyText:"Lo stesso produttore di autoradio può fornire più case automobilistiche.",faq:"Domande frequenti",q1:"Il seriale identifica sempre l’auto?",a1:"No. Alcune famiglie sono condivise.",q2:"Tutte le radio mostrano il seriale?",a2:"No. Molte richiedono l’etichetta fisica.",q3:"Esiste un generatore universale?",a3:"No. Il metodo dipende dalla famiglia della radio."},
};

export default function PremiumHomeV3() {
  const [language, setLanguage] = useState<Language>("es");
  const [menuOpen, setMenuOpen] = useState(false);
  const t = strings[language];

  return (
    <main id="top" className="min-h-screen bg-white text-slate-950">
      <div className="bg-[#071a36] px-5 py-2 text-center text-xs font-bold text-blue-100 md:text-sm">
        <span className="mx-3">✓ Identificación por serie</span><span className="mx-3 hidden sm:inline">🔒 Pago seguro con PayPal</span><span className="mx-3 hidden md:inline">🌐 6 idiomas</span>
      </div>

      <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 px-5 py-3 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-3">
          <button onClick={()=>setMenuOpen(!menuOpen)} className="rounded-lg px-2 py-2 text-sm font-bold text-slate-600 md:hidden">☰</button>
          <Link href="/" className="font-black tracking-tight"><span className="mr-2 inline-flex h-9 w-9 items-center justify-center rounded-full bg-blue-600 text-[10px] text-white">ASC</span>AUTO STEREO CODES</Link>
          <nav className="hidden items-center gap-5 text-sm font-bold text-slate-600 md:flex">
            <Link href="/radio-codes" className="hover:text-blue-700">{t.all}</Link>
            <a href="#how" className="hover:text-blue-700">{t.how}</a>
            <a href="#serial-matcher" className="hover:text-blue-700">{t.serial}</a>
            <a href="#faq" className="hover:text-blue-700">{t.help}</a>
          </nav>
          <div className="flex items-center gap-2">
            <select value={language} onChange={(e)=>setLanguage(e.target.value as Language)} className="max-w-28 rounded-lg border border-slate-200 bg-white px-2 py-2 text-xs font-bold outline-none sm:max-w-none">
              {languageOptions.map((option)=><option key={option.code} value={option.code}>{option.flag} {option.label}</option>)}
            </select>
            <a href="#request-form" className="hidden rounded-full bg-blue-600 px-4 py-2 text-sm font-black text-white hover:bg-blue-500 sm:inline-flex">{t.order}</a>
          </div>
        </div>
        {menuOpen && <div className="mx-auto mt-3 grid max-w-7xl gap-2 border-t border-slate-100 pt-3 text-sm font-bold md:hidden"><Link onClick={()=>setMenuOpen(false)} href="/radio-codes" className="rounded-lg px-3 py-2 hover:bg-slate-50">{t.all}</Link><a onClick={()=>setMenuOpen(false)} href="#how" className="rounded-lg px-3 py-2 hover:bg-slate-50">{t.how}</a><a onClick={()=>setMenuOpen(false)} href="#serial-matcher" className="rounded-lg px-3 py-2 hover:bg-slate-50">{t.serial}</a><a onClick={()=>setMenuOpen(false)} href="#request-form" className="rounded-lg px-3 py-2 text-blue-700">{t.order}</a></div>}
      </header>

      <section className="relative min-h-[650px] overflow-hidden bg-slate-950 text-white">
        <img src={HERO_IMAGE} alt="Interior de automóvil con sistema de audio" className="absolute inset-0 h-full w-full object-cover" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,10,24,.94)_0%,rgba(4,18,43,.82)_44%,rgba(4,18,43,.5)_100%)]" />
        <div className="relative mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-[1fr_.9fr] lg:items-center lg:py-24">
          <div>
            <div className="inline-flex rounded-full border border-blue-300/25 bg-blue-400/10 px-4 py-2 text-xs font-black tracking-[.16em] text-blue-200">{t.badge}</div>
            <h1 className="mt-7 max-w-3xl text-5xl font-black leading-[.98] tracking-tight md:text-7xl">{t.heroA}<br/><span className="text-blue-400">{t.heroB}</span></h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{t.heroText}</p>
            <div className="mt-7 flex flex-wrap gap-3"><Link href="/radio-codes" className="rounded-xl bg-blue-600 px-6 py-3.5 font-black hover:bg-blue-500">{t.all} →</Link><a href="#serial-help" className="rounded-xl border border-white/20 bg-white/5 px-6 py-3.5 font-bold hover:bg-white/10">{t.guide}</a></div>
          </div>
          <div id="serial-matcher" className="scroll-mt-28 rounded-[2rem] border border-white/15 bg-white/95 p-2 text-slate-950 shadow-2xl backdrop-blur"><UniversalSerialFinder language={language} compact /></div>
        </div>
      </section>

      <section className="overflow-hidden border-y border-slate-200 bg-slate-50 py-5">
        <div className="mx-auto max-w-7xl px-6"><div className="mb-3 text-center text-[11px] font-black uppercase tracking-[.2em] text-slate-400">{t.ticker}</div></div>
        <div className="brand-track flex w-max gap-3 px-3">{[...tickerBrands,...tickerBrands].map((brand,index)=><span key={`${brand}-${index}`} className="flex h-12 min-w-36 items-center justify-center rounded-xl border border-slate-200 bg-white px-5 text-sm font-black text-slate-700 shadow-sm">{brand}</span>)}</div>
      </section>

      <section className="px-6 py-20 md:py-24">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
          <div><p className="text-sm font-black uppercase tracking-[.2em] text-blue-600">36 GUÍAS</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">{t.allTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{t.allText}</p><Link href="/radio-codes" className="mt-7 inline-flex rounded-xl bg-slate-950 px-6 py-4 font-black text-white hover:bg-blue-700">{t.explore}</Link></div>
          <div className="grid gap-3 sm:grid-cols-2">{[["Honda / Acura","U/L · S/N · Touchscreen"],["Ford / Sony","V · M · SN · C7"],["VW / Audi / SEAT / Škoda","VWZ · AUZ · SEZ · SKZ"],["Jeep / Chrysler / Dodge","T-series · A2C"],["Nissan","CL · PN · BP · DW · Connect"],["Fiat / Alfa / Lancia","BP · 815CM · A2C · Daiichi"]].map(([a,b])=><div key={a} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="font-black">{a}</div><div className="mt-2 font-mono text-xs font-bold text-blue-700">{b}</div></div>)}</div>
        </div>
      </section>

      <section id="how" className="bg-[#0b2347] px-6 py-20 text-white md:py-24"><div className="mx-auto max-w-7xl"><h2 className="max-w-3xl text-4xl font-black md:text-5xl">{t.stepsTitle}</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[[t.step1,t.step1t],[t.step2,t.step2t],[t.step3,t.step3t]].map(([a,b],index)=><div key={a} className="rounded-3xl border border-white/10 bg-white/5 p-7"><div className="text-4xl font-black text-blue-400">0{index+1}</div><h3 className="mt-5 text-xl font-black">{a}</h3><p className="mt-3 leading-7 text-blue-100/70">{b}</p></div>)}</div></div></section>

      <section className="px-6 py-20 md:py-24"><div className="mx-auto max-w-5xl text-center"><p className="text-sm font-black uppercase tracking-[.2em] text-blue-600">RADIO-FIRST</p><h2 className="mt-3 text-4xl font-black md:text-5xl">{t.whyTitle}</h2><p className="mx-auto mt-5 max-w-4xl text-lg leading-8 text-slate-600">{t.whyText}</p></div></section>

      <section id="faq" className="bg-slate-50 px-6 py-20"><div className="mx-auto max-w-4xl"><h2 className="text-4xl font-black">{t.faq}</h2><div className="mt-8 space-y-3">{[[t.q1,t.a1],[t.q2,t.a2],[t.q3,t.a3]].map(([q,a])=><details key={q} className="group rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer list-none font-black">{q}<span className="float-right text-blue-600 group-open:rotate-45">＋</span></summary><p className="mt-4 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>

      <CheckoutRequestForm language={language} />

      <footer className="bg-[#06152d] px-6 py-10 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="font-black text-white">AUTO STEREO CODES</div><div className="mt-1 text-sm">Servicio independiente de códigos para radios de automóvil.</div></div><div className="flex flex-wrap gap-4 text-sm font-bold"><Link href="/radio-codes" className="hover:text-white">{t.all}</Link><a href="#serial-matcher" className="hover:text-white">{t.serial}</a><a href="#request-form" className="hover:text-white">{t.order}</a></div></div></footer>

      <style jsx>{`@keyframes brands { from { transform: translateX(0); } to { transform: translateX(-50%); } } .brand-track { animation: brands 38s linear infinite; } .brand-track:hover { animation-play-state: paused; }`}</style>
    </main>
  );
}
