"use client";

import { useState } from "react";
import UniversalSerialFinderV2 from "./UniversalSerialFinderV2";
import { languageOptions, type Language } from "./languages";
import { HOME_CAR_PHOTO, RADIO_INTERIOR_PHOTO } from "./brandVisuals";

const HERO_IMAGE=HOME_CAR_PHOTO;
const tickerBrands=["HONDA","ACURA","FORD","VOLKSWAGEN","AUDI","SEAT","ŠKODA","NISSAN","RENAULT","DACIA","TOYOTA","LEXUS","FIAT","ALFA ROMEO","LANCIA","PEUGEOT","CITROËN","MERCEDES-BENZ","BMW","JEEP","CHRYSLER","DODGE","LAND ROVER","JAGUAR","PORSCHE","SUZUKI"];

const copy={
  es:{all:"Todas las marcas",how:"Cómo funciona",serial:"Encontrar serie",help:"Centro de ayuda",request:"Solicitar código",badge:"IDENTIFICA · CONFIRMA · SOLICITA",h1a:"Encuentra tu radio",h1b:"antes de pagar.",hero:"Escribe la serie de tu estéreo. Las marcas compatibles aparecerán automáticamente y podrás abrir una guía específica para tu vehículo.",guide:"No sé cuál es mi número de serie",ticker:"Marcas y familias compatibles",howTitle:"Un proceso más claro",s1:"Escribe tu serie",s1t:"No hay botón de búsqueda. El sistema analiza el formato automáticamente mientras escribes.",s2:"Elige tu marca",s2t:"Si una misma serie aparece en varias marcas, verás botones separados para Honda, Acura, Jeep, Chrysler y las demás opciones posibles.",s3:"Abre la guía exacta",s3t:"Cada marca tiene su propia pantalla con métodos por tipo de estéreo, ejemplos y advertencias.",s4:"Completa tu solicitud",s4t:"La solicitud ahora vive en una página separada, más limpia y profesional.",helpTitle:"Encuentra la serie correcta antes de comprar",helpText:"Consulta el directorio completo de marcas o entra directamente a la guía de tu vehículo.",open:"Abrir todas las marcas",cta:"¿Ya tienes la serie correcta?",ctaText:"Ve directamente a la solicitud y completa el correo donde quieres recibir tu código.",footer:"Servicio independiente de códigos de radio. Las marcas comerciales pertenecen a sus respectivos propietarios."},
  en:{all:"All brands",how:"How it works",serial:"Find serial",help:"Help centre",request:"Request code",badge:"IDENTIFY · CONFIRM · REQUEST",h1a:"Find your radio",h1b:"before you pay.",hero:"Type your stereo serial. Compatible vehicle brands appear automatically and you can open the exact guide for your vehicle.",guide:"I don't know my serial number",ticker:"Supported brands and radio families",howTitle:"A clearer process",s1:"Type your serial",s1t:"There is no search button. The format is analysed automatically while you type.",s2:"Choose your brand",s2t:"If one serial appears in several brands, you will see separate buttons for every possible vehicle.",s3:"Open the exact guide",s3t:"Each brand has its own page with methods by stereo type, examples and warnings.",s4:"Complete your request",s4t:"The order form now lives on a separate, cleaner page.",helpTitle:"Find the right serial before you buy",helpText:"Browse the complete brand directory or go straight to your vehicle guide.",open:"Open all brands",cta:"Already have the correct serial?",ctaText:"Go straight to the request page and enter the email where you want to receive your code.",footer:"Independent radio-code service. Vehicle and radio trademarks belong to their respective owners."},
};

export default function PremiumHomeV4(){
  const [language,setLanguage]=useState<Language>("es");
  const [menuOpen,setMenuOpen]=useState(false);
  const base=language==="es"?copy.es:copy.en;
  return <main className="min-h-screen bg-[#fffaf5] text-slate-950">
    <style>{`@keyframes asc-marquee{from{transform:translateX(0)}to{transform:translateX(-50%)}} .asc-marquee{animation:asc-marquee 34s linear infinite}.asc-marquee:hover{animation-play-state:paused}`}</style>
    <header className="sticky top-0 z-50 border-b border-orange-100 bg-white/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 lg:px-8">
        <a href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-orange-500 text-xs font-black text-white">ASC</span><span className="font-black tracking-tight">AUTO STEREO CODES</span></a>
        <nav className="hidden items-center gap-6 lg:flex"><a href="/radio-codes" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.all}</a><a href="#how" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.how}</a><a href="/radio-codes" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.serial}</a><a href="#help" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.help}</a></nav>
        <div className="flex items-center gap-2"><select value={language} onChange={e=>setLanguage(e.target.value as Language)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold">{languageOptions.map(x=><option key={x.code} value={x.code}>{x.flag} {x.label}</option>)}</select><a href="/request" className="hidden rounded-full bg-orange-500 px-5 py-3 text-sm font-black text-white shadow-sm hover:bg-orange-600 sm:inline-flex">{base.request}</a><button onClick={()=>setMenuOpen(v=>!v)} className="rounded-xl border border-slate-200 px-3 py-2 font-black lg:hidden">☰</button></div>
      </div>
      {menuOpen&&<div className="border-t border-slate-100 bg-white px-5 py-4 lg:hidden"><div className="mx-auto grid max-w-7xl gap-2"><a href="/radio-codes" className="rounded-xl px-3 py-3 font-bold hover:bg-orange-50">{base.all}</a><a href="#how" className="rounded-xl px-3 py-3 font-bold hover:bg-orange-50">{base.how}</a><a href="#help" className="rounded-xl px-3 py-3 font-bold hover:bg-orange-50">{base.help}</a><a href="/request" className="rounded-xl bg-orange-500 px-3 py-3 text-center font-black text-white">{base.request}</a></div></div>}
    </header>

    <section className="relative overflow-hidden border-b border-orange-100 bg-white">
      <div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`url(${HERO_IMAGE})`}}/>
      <div className="absolute inset-0 bg-gradient-to-r from-white/97 via-white/88 to-orange-50/74"/>
      <div className="absolute inset-y-0 right-0 w-1/2 bg-gradient-to-l from-orange-100/30 to-transparent"/>
      <div className="relative mx-auto grid min-h-[680px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[.95fr_1.05fr] lg:px-8">
        <div><div className="inline-flex rounded-full border border-orange-200 bg-white/80 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-orange-700 shadow-sm backdrop-blur">{base.badge}</div><h1 className="mt-6 max-w-2xl text-5xl font-black leading-[.98] tracking-tight md:text-7xl">{base.h1a}<br/><span className="text-orange-500">{base.h1b}</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-700">{base.hero}</p><div className="mt-8 flex flex-wrap gap-3"><a href="/radio-codes" className="rounded-xl bg-orange-500 px-6 py-4 font-black text-white shadow-lg shadow-orange-200 hover:bg-orange-600">{base.all} →</a><a href="/radio-codes" className="rounded-xl border border-slate-300 bg-white/90 px-6 py-4 font-black text-slate-800 backdrop-blur hover:border-orange-300">{base.guide}</a></div></div>
        <UniversalSerialFinderV2 language={language}/>
      </div>
      <div className="absolute bottom-3 left-4 rounded-full bg-white/75 px-3 py-1 text-[10px] font-semibold text-slate-600 backdrop-blur">Foto de vehículo: Unsplash</div>
    </section>

    <section className="overflow-hidden border-b border-orange-100 bg-white py-7"><div className="mx-auto mb-5 max-w-7xl px-5 text-center text-xs font-black uppercase tracking-[.2em] text-slate-400">{base.ticker}</div><div className="asc-marquee flex w-max gap-3">{[...tickerBrands,...tickerBrands].map((name,i)=><div key={`${name}-${i}`} className="flex h-12 min-w-36 items-center justify-center rounded-full border border-orange-100 bg-orange-50/60 px-5 text-sm font-black text-slate-700">{name}</div>)}</div></section>

    <section id="how" className="bg-[#fffaf5] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="text-center"><div className="text-xs font-black uppercase tracking-[.2em] text-orange-500">AUTO STEREO CODES</div><h2 className="mt-3 text-4xl font-black md:text-5xl">{base.howTitle}</h2></div><div className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[["01",base.s1,base.s1t],["02",base.s2,base.s2t],["03",base.s3,base.s3t],["04",base.s4,base.s4t]].map(([n,a,b])=><article key={n} className="rounded-3xl border border-orange-100 bg-white p-7 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-500 font-black text-white">{n}</div><h3 className="mt-5 text-xl font-black">{a}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{b}</p></article>)}</div></div></section>

    <section id="help" className="relative overflow-hidden bg-white py-24"><div className="absolute inset-y-0 right-0 hidden w-[48%] bg-cover bg-center opacity-[0.13] lg:block" style={{backgroundImage:`url(${RADIO_INTERIOR_PHOTO})`}}/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/96 to-white/78"/><div className="relative mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-[1fr_.85fr] lg:items-center lg:px-8"><div><div className="text-xs font-black uppercase tracking-[.2em] text-orange-500">GUIDES</div><h2 className="mt-3 text-4xl font-black md:text-5xl">{base.helpTitle}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{base.helpText}</p><a href="/radio-codes" className="mt-7 inline-flex rounded-xl bg-slate-950 px-6 py-4 font-black text-white hover:bg-slate-800">{base.open} →</a></div><div className="grid gap-4 sm:grid-cols-2">{["Honda / Acura","Ford / Visteon","Jeep / Chrysler / Dodge","Volkswagen / Audi","Nissan / Clarion","Renault / Dacia"].map(x=><div key={x} className="rounded-3xl border border-orange-100 bg-white/88 p-6 shadow-sm backdrop-blur"><div className="text-2xl">🚘</div><div className="mt-4 font-black">{x}</div><div className="mt-2 text-sm text-slate-500">Guía por tipo de estéreo, prefijo y método de serie.</div></div>)}</div></div></section>

    <section className="bg-orange-500 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 md:flex-row md:items-center md:justify-between lg:px-8"><div><h2 className="text-3xl font-black md:text-4xl">{base.cta}</h2><p className="mt-2 max-w-2xl text-orange-50">{base.ctaText}</p></div><a href="/request" className="inline-flex shrink-0 rounded-xl bg-white px-6 py-4 font-black text-slate-950 shadow-lg">{base.request} →</a></div></section>

    <footer className="border-t border-orange-100 bg-white px-5 py-10 text-slate-500"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="font-black text-slate-950">AUTO <span className="text-orange-500">STEREO</span> CODES</div><div className="max-w-2xl text-xs leading-5">{base.footer}</div></div></footer>
  </main>;
}
