"use client";

import { useEffect, useState } from "react";
import UniversalSerialFinderV2 from "./UniversalSerialFinderV2";
import { languageOptions, type Language } from "./languages";
import { HOME_CAR_PHOTO, RADIO_INTERIOR_PHOTO, brandPhotoForSlug } from "./brandVisuals";

const HERO_IMAGE=HOME_CAR_PHOTO;
const tickerBrands=["HONDA","ACURA","FORD","VOLKSWAGEN","AUDI","SEAT","ŠKODA","NISSAN","RENAULT","DACIA","TOYOTA","LEXUS","FIAT","ALFA ROMEO","LANCIA","PEUGEOT","CITROËN","MERCEDES-BENZ","BMW","JEEP","CHRYSLER","DODGE","LAND ROVER","JAGUAR","PORSCHE","SUZUKI"];
const guideCards=[
  {title:"Honda / Acura",slug:"honda"},
  {title:"Ford / Visteon",slug:"ford"},
  {title:"Jeep / Chrysler / Dodge",slug:"jeep"},
  {title:"Volkswagen / Audi",slug:"volkswagen"},
  {title:"Nissan / Clarion",slug:"nissan"},
  {title:"Renault / Dacia",slug:"renault"},
];

const copy={
  es:{all:"Todas las marcas",how:"Cómo funciona",serial:"Encontrar serie",help:"Centro de ayuda",request:"Solicitar código",badge:"IDENTIFICA · CONFIRMA · SOLICITA",h1a:"Encuentra tu radio",h1b:"antes de pagar.",hero:"Escribe la serie de tu estéreo. Las marcas compatibles aparecerán automáticamente y podrás abrir una guía específica para tu vehículo.",guide:"No sé cuál es mi número de serie",ticker:"Marcas y familias compatibles",howTitle:"Un proceso más claro",s1:"Escribe tu serie",s1t:"No hay botón de búsqueda. El sistema analiza el formato automáticamente mientras escribes.",s2:"Elige tu marca",s2t:"Si una misma serie aparece en varias marcas, verás botones separados para cada opción posible.",s3:"Abre la guía exacta",s3t:"Cada marca tiene su propia pantalla con métodos por tipo de estéreo, ejemplos y advertencias.",s4:"Completa tu solicitud",s4t:"La solicitud vive en una página separada, más limpia y profesional.",helpTitle:"Encuentra la serie correcta antes de comprar",helpText:"Consulta el directorio completo de marcas o entra directamente a la guía de tu vehículo.",open:"Abrir todas las marcas",guides:"GUÍAS",guideCard:"Guía por tipo de estéreo, prefijo y método de serie.",cta:"¿Ya tienes la serie correcta?",ctaText:"Ve directamente a la solicitud y completa el correo donde quieres recibir tu código.",footer:"Servicio independiente de códigos de radio. Las marcas comerciales pertenecen a sus respectivos propietarios."},
  en:{all:"All brands",how:"How it works",serial:"Find serial",help:"Help centre",request:"Request code",badge:"IDENTIFY · CONFIRM · REQUEST",h1a:"Find your radio",h1b:"before you pay.",hero:"Type your stereo serial. Compatible vehicle brands appear automatically and you can open the exact guide for your vehicle.",guide:"I don't know my serial number",ticker:"Supported brands and radio families",howTitle:"A clearer process",s1:"Type your serial",s1t:"There is no search button. The format is analysed automatically while you type.",s2:"Choose your brand",s2t:"If one serial appears in several brands, you will see separate buttons for every possible vehicle.",s3:"Open the exact guide",s3t:"Each brand has its own page with methods by stereo type, examples and warnings.",s4:"Complete your request",s4t:"The order form lives on a separate, cleaner page.",helpTitle:"Find the right serial before you buy",helpText:"Browse the complete brand directory or go straight to your vehicle guide.",open:"Open all brands",guides:"GUIDES",guideCard:"Guide by stereo type, serial prefix and retrieval method.",cta:"Already have the correct serial?",ctaText:"Go straight to the request page and enter the email where you want to receive your code.",footer:"Independent radio-code service. Vehicle and radio trademarks belong to their respective owners."},
  pt:{all:"Todas as marcas",how:"Como funciona",serial:"Encontrar serial",help:"Central de ajuda",request:"Solicitar código",badge:"IDENTIFIQUE · CONFIRME · SOLICITE",h1a:"Encontre seu rádio",h1b:"antes de pagar.",hero:"Digite o número de série do seu rádio. As marcas compatíveis aparecerão automaticamente e você poderá abrir o guia exato do seu veículo.",guide:"Não sei qual é o meu número de série",ticker:"Marcas e famílias de rádio compatíveis",howTitle:"Um processo mais claro",s1:"Digite o serial",s1t:"Não há botão de busca. O sistema analisa o formato automaticamente enquanto você digita.",s2:"Escolha a marca",s2t:"Se o mesmo serial aparecer em várias marcas, você verá uma opção separada para cada veículo possível.",s3:"Abra o guia correto",s3t:"Cada marca tem sua própria página com métodos por tipo de rádio, exemplos e avisos.",s4:"Complete a solicitação",s4t:"O formulário de pedido fica em uma página separada, mais limpa e profissional.",helpTitle:"Encontre o serial correto antes de comprar",helpText:"Consulte o diretório completo de marcas ou abra diretamente o guia do seu veículo.",open:"Abrir todas as marcas",guides:"GUIAS",guideCard:"Guia por tipo de rádio, prefixo do serial e método de localização.",cta:"Já tem o serial correto?",ctaText:"Vá direto para a solicitação e informe o e-mail onde deseja receber o código.",footer:"Serviço independente de códigos de rádio. As marcas pertencem aos seus respectivos proprietários."},
  fr:{all:"Toutes les marques",how:"Comment ça marche",serial:"Trouver le numéro",help:"Centre d’aide",request:"Demander le code",badge:"IDENTIFIER · CONFIRMER · DEMANDER",h1a:"Trouvez votre autoradio",h1b:"avant de payer.",hero:"Saisissez le numéro de série de votre autoradio. Les marques compatibles apparaîtront automatiquement et vous pourrez ouvrir le guide exact de votre véhicule.",guide:"Je ne connais pas mon numéro de série",ticker:"Marques et familles d’autoradios compatibles",howTitle:"Un processus plus clair",s1:"Saisissez le numéro",s1t:"Aucun bouton de recherche n’est nécessaire. Le système analyse automatiquement le format pendant la saisie.",s2:"Choisissez la marque",s2t:"Si un même numéro peut correspondre à plusieurs marques, chaque véhicule possible sera proposé séparément.",s3:"Ouvrez le guide exact",s3t:"Chaque marque possède sa propre page avec des méthodes selon le type d’autoradio, des exemples et des avertissements.",s4:"Complétez la demande",s4t:"Le formulaire de commande se trouve sur une page séparée, plus claire et professionnelle.",helpTitle:"Trouvez le bon numéro avant d’acheter",helpText:"Consultez le répertoire complet des marques ou ouvrez directement le guide de votre véhicule.",open:"Voir toutes les marques",guides:"GUIDES",guideCard:"Guide par type d’autoradio, préfixe de série et méthode de recherche.",cta:"Vous avez déjà le bon numéro ?",ctaText:"Accédez directement à la demande et indiquez l’e-mail où vous souhaitez recevoir votre code.",footer:"Service indépendant de codes autoradio. Les marques appartiennent à leurs propriétaires respectifs."},
  de:{all:"Alle Marken",how:"So funktioniert es",serial:"Seriennummer finden",help:"Hilfe-Center",request:"Code anfordern",badge:"ERKENNEN · BESTÄTIGEN · ANFORDERN",h1a:"Finde dein Radio",h1b:"bevor du bezahlst.",hero:"Gib die Seriennummer deines Radios ein. Passende Fahrzeugmarken erscheinen automatisch und du kannst die genaue Anleitung für dein Fahrzeug öffnen.",guide:"Ich kenne meine Seriennummer nicht",ticker:"Unterstützte Marken und Radiofamilien",howTitle:"Ein klarerer Ablauf",s1:"Seriennummer eingeben",s1t:"Es gibt keinen Suchknopf. Das Format wird während der Eingabe automatisch analysiert.",s2:"Marke auswählen",s2t:"Wenn eine Seriennummer bei mehreren Marken vorkommt, werden die möglichen Fahrzeuge getrennt angezeigt.",s3:"Passende Anleitung öffnen",s3t:"Jede Marke hat eine eigene Seite mit Methoden je Radiotyp, Beispielen und Hinweisen.",s4:"Anfrage abschließen",s4t:"Das Bestellformular befindet sich auf einer separaten, übersichtlichen Seite.",helpTitle:"Finde die richtige Seriennummer vor dem Kauf",helpText:"Durchsuche das vollständige Markenverzeichnis oder öffne direkt die Anleitung für dein Fahrzeug.",open:"Alle Marken öffnen",guides:"ANLEITUNGEN",guideCard:"Anleitung nach Radiotyp, Serienpräfix und Methode zum Auffinden.",cta:"Hast du bereits die richtige Seriennummer?",ctaText:"Öffne direkt die Anfrage und gib die E-Mail-Adresse an, an die dein Code gesendet werden soll.",footer:"Unabhängiger Radio-Code-Service. Fahrzeug- und Radiomarken gehören ihren jeweiligen Eigentümern."},
  it:{all:"Tutti i marchi",how:"Come funziona",serial:"Trova il seriale",help:"Centro assistenza",request:"Richiedi codice",badge:"IDENTIFICA · CONFERMA · RICHIEDI",h1a:"Trova la tua autoradio",h1b:"prima di pagare.",hero:"Inserisci il numero di serie dell’autoradio. I marchi compatibili appariranno automaticamente e potrai aprire la guida esatta per il tuo veicolo.",guide:"Non conosco il mio numero di serie",ticker:"Marchi e famiglie di autoradio compatibili",howTitle:"Un processo più chiaro",s1:"Inserisci il seriale",s1t:"Non c’è alcun pulsante di ricerca. Il sistema analizza automaticamente il formato mentre scrivi.",s2:"Scegli il marchio",s2t:"Se lo stesso seriale compare su più marchi, vedrai un’opzione separata per ogni veicolo possibile.",s3:"Apri la guida esatta",s3t:"Ogni marchio ha una propria pagina con metodi per tipo di autoradio, esempi e avvertenze.",s4:"Completa la richiesta",s4t:"Il modulo d’ordine si trova in una pagina separata, più pulita e professionale.",helpTitle:"Trova il seriale corretto prima dell’acquisto",helpText:"Consulta l’elenco completo dei marchi oppure apri direttamente la guida del tuo veicolo.",open:"Apri tutti i marchi",guides:"GUIDE",guideCard:"Guida per tipo di autoradio, prefisso del seriale e metodo di ricerca.",cta:"Hai già il seriale corretto?",ctaText:"Vai direttamente alla richiesta e inserisci l’e-mail su cui vuoi ricevere il codice.",footer:"Servizio indipendente di codici autoradio. I marchi appartengono ai rispettivi proprietari."},
} as const;

export default function PremiumHomeV4(){
  const [language,setLanguage]=useState<Language>("es");
  const [menuOpen,setMenuOpen]=useState(false);
  const base=copy[language];

  useEffect(()=>{
    const elements=Array.from(document.querySelectorAll<HTMLElement>(".asc-reveal"));
    if(!("IntersectionObserver" in window)) { elements.forEach(el=>el.classList.add("asc-visible")); return; }
    const observer=new IntersectionObserver(entries=>{
      entries.forEach(entry=>{
        if(entry.isIntersecting){ entry.target.classList.add("asc-visible"); observer.unobserve(entry.target); }
      });
    },{threshold:0.12,rootMargin:"0px 0px -45px 0px"});
    elements.forEach(el=>observer.observe(el));
    return()=>observer.disconnect();
  },[]);

  return <main className="min-h-screen bg-[#fffaf5] text-slate-950">
    <style>{`
      @keyframes asc-marquee{from{transform:translateX(0)}to{transform:translateX(-50%)}}
      @keyframes asc-rise{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}
      @keyframes asc-soft-pop{0%{opacity:0;transform:translateY(16px) scale(.985)}100%{opacity:1;transform:translateY(0) scale(1)}}
      .asc-marquee{animation:asc-marquee 64s linear infinite}.asc-marquee:hover{animation-play-state:paused}
      .asc-hero{opacity:0;animation:asc-rise .82s cubic-bezier(.2,.7,.2,1) forwards}
      .asc-reveal{opacity:0;transform:translateY(32px);filter:blur(5px);transition:opacity .8s ease,transform .8s cubic-bezier(.2,.7,.2,1),filter .8s ease}
      .asc-reveal.asc-visible{opacity:1;transform:translateY(0);filter:blur(0)}
      .asc-card{transition:transform .35s ease,box-shadow .35s ease,border-color .35s ease}.asc-card:hover{transform:translateY(-5px);box-shadow:0 18px 45px rgba(15,23,42,.10)}
      @media (prefers-reduced-motion:reduce){.asc-marquee{animation:none}.asc-hero,.asc-reveal{opacity:1!important;transform:none!important;filter:none!important;animation:none!important;transition:none!important}}
    `}</style>
    <header className="sticky top-0 z-50 border-b border-orange-100 bg-white/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 lg:px-8">
        <a href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-orange-500 text-xs font-black text-white">ASC</span><span className="font-black tracking-tight">AUTO STEREO CODES</span></a>
        <nav className="hidden items-center gap-6 lg:flex"><a href="/radio-codes" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.all}</a><a href="#how" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.how}</a><a href="/radio-codes" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.serial}</a><a href="#help" className="text-sm font-bold text-slate-600 hover:text-orange-600">{base.help}</a></nav>
        <div className="flex items-center gap-2"><select value={language} onChange={e=>setLanguage(e.target.value as Language)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold">{languageOptions.map(x=><option key={x.code} value={x.code}>{x.flag} {x.label}</option>)}</select><a href="/request" className="hidden rounded-full bg-orange-500 px-5 py-3 text-sm font-black text-white shadow-sm hover:bg-orange-600 sm:inline-flex">{base.request}</a><button onClick={()=>setMenuOpen(v=>!v)} className="rounded-xl border border-slate-200 px-3 py-2 font-black lg:hidden">☰</button></div>
      </div>
      {menuOpen&&<div className="border-t border-slate-100 bg-white px-5 py-4 lg:hidden"><div className="mx-auto grid max-w-7xl gap-2"><a href="/radio-codes" className="rounded-xl px-3 py-3 font-bold hover:bg-orange-50">{base.all}</a><a href="#how" className="rounded-xl px-3 py-3 font-bold hover:bg-orange-50">{base.how}</a><a href="#help" className="rounded-xl px-3 py-3 font-bold hover:bg-orange-50">{base.help}</a><a href="/request" className="rounded-xl bg-orange-500 px-3 py-3 text-center font-black text-white">{base.request}</a></div></div>}
    </header>

    <section className="relative overflow-hidden border-b border-orange-100 bg-white">
      <div className="absolute inset-0 bg-cover opacity-55" style={{backgroundImage:`url(${HERO_IMAGE})`,backgroundPosition:"center 56%"}}/>
      <div className="absolute inset-0 bg-gradient-to-r from-[#fffaf5]/96 via-[#fffaf5]/72 to-white/36"/>
      <div className="absolute inset-0 bg-gradient-to-b from-white/10 via-transparent to-orange-50/35"/>
      <div className="absolute inset-y-0 right-0 w-[46%] bg-gradient-to-l from-orange-100/16 to-transparent"/>
      <div className="relative mx-auto grid min-h-[680px] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[.95fr_1.05fr] lg:px-8">
        <div><div className="asc-hero inline-flex rounded-full border border-orange-200 bg-white/80 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-orange-700 shadow-sm backdrop-blur" style={{animationDelay:".05s"}}>{base.badge}</div><h1 className="asc-hero mt-6 max-w-2xl text-5xl font-black leading-[.98] tracking-tight md:text-7xl" style={{animationDelay:".14s"}}>{base.h1a}<br/><span className="text-orange-500">{base.h1b}</span></h1><p className="asc-hero mt-7 max-w-xl text-lg leading-8 text-slate-700" style={{animationDelay:".24s"}}>{base.hero}</p><div className="asc-hero mt-8 flex flex-wrap gap-3" style={{animationDelay:".34s"}}><a href="/radio-codes" className="rounded-xl bg-orange-500 px-6 py-4 font-black text-white shadow-lg shadow-orange-200 hover:bg-orange-600">{base.all} →</a><a href="/radio-codes" className="rounded-xl border border-slate-300 bg-white/90 px-6 py-4 font-black text-slate-800 backdrop-blur hover:border-orange-300">{base.guide}</a></div></div>
        <div className="asc-hero rounded-[2.4rem] bg-white/55 p-2 shadow-2xl shadow-slate-900/10 backdrop-blur-[2px]" style={{animationDelay:".28s"}}><UniversalSerialFinderV2 language={language}/></div>
      </div>
      <div className="absolute bottom-3 left-4 rounded-full bg-white/75 px-3 py-1 text-[10px] font-semibold text-slate-600 backdrop-blur">Foto de vehículo: Unsplash</div>
    </section>

    <section className="overflow-hidden border-b border-orange-100 bg-white py-7"><div className="asc-reveal mx-auto mb-5 max-w-7xl px-5 text-center text-xs font-black uppercase tracking-[.2em] text-slate-400">{base.ticker}</div><div className="asc-marquee flex w-max gap-3">{[...tickerBrands,...tickerBrands].map((name,i)=><div key={`${name}-${i}`} className="flex h-12 min-w-36 items-center justify-center rounded-full border border-orange-100 bg-orange-50/60 px-5 text-sm font-black text-slate-700">{name}</div>)}</div></section>

    <section id="how" className="bg-[#fffaf5] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="asc-reveal text-center"><div className="text-xs font-black uppercase tracking-[.2em] text-orange-500">AUTO STEREO CODES</div><h2 className="mt-3 text-4xl font-black md:text-5xl">{base.howTitle}</h2></div><div className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[["01",base.s1,base.s1t],["02",base.s2,base.s2t],["03",base.s3,base.s3t],["04",base.s4,base.s4t]].map(([n,a,b],i)=><article key={n} className="asc-reveal asc-card rounded-3xl border border-orange-100 bg-white p-7 shadow-sm" style={{transitionDelay:`${i*85}ms`}}><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-500 font-black text-white">{n}</div><h3 className="mt-5 text-xl font-black">{a}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{b}</p></article>)}</div></div></section>

    <section id="help" className="relative overflow-hidden bg-white py-24"><div className="absolute inset-y-0 right-0 hidden w-[48%] bg-cover bg-center opacity-[0.13] lg:block" style={{backgroundImage:`url(${RADIO_INTERIOR_PHOTO})`}}/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/96 to-white/78"/><div className="relative mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-[1fr_.95fr] lg:items-center lg:px-8"><div className="asc-reveal"><div className="text-xs font-black uppercase tracking-[.2em] text-orange-500">{base.guides}</div><h2 className="mt-3 text-4xl font-black md:text-5xl">{base.helpTitle}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{base.helpText}</p><a href="/radio-codes" className="mt-7 inline-flex rounded-xl bg-slate-950 px-6 py-4 font-black text-white hover:bg-slate-800">{base.open} →</a></div><div className="grid gap-4 sm:grid-cols-2">{guideCards.map((item,i)=><div key={item.title} className="asc-reveal asc-card overflow-hidden rounded-3xl border border-orange-100 bg-white/92 shadow-sm backdrop-blur" style={{transitionDelay:`${i*70}ms`}}><div className="relative h-28 overflow-hidden"><div className="absolute inset-0 bg-cover bg-center transition duration-500 hover:scale-105" style={{backgroundImage:`url(${brandPhotoForSlug(item.slug)})`}}/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/65 via-slate-950/10 to-transparent"/><div className="absolute bottom-3 left-4 font-black text-white drop-shadow">{item.title}</div></div><div className="p-5"><div className="text-sm leading-6 text-slate-500">{base.guideCard}</div></div></div>)}</div></div></section>

    <section className="bg-orange-500 py-16 text-white"><div className="asc-reveal mx-auto flex max-w-7xl flex-col gap-6 px-5 md:flex-row md:items-center md:justify-between lg:px-8"><div><h2 className="text-3xl font-black md:text-4xl">{base.cta}</h2><p className="mt-2 max-w-2xl text-orange-50">{base.ctaText}</p></div><a href="/request" className="inline-flex shrink-0 rounded-xl bg-white px-6 py-4 font-black text-slate-950 shadow-lg transition hover:-translate-y-1">{base.request} →</a></div></section>

    <footer className="border-t border-orange-100 bg-white px-5 py-10 text-slate-500"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="font-black text-slate-950">AUTO <span className="text-orange-500">STEREO</span> CODES</div><div className="max-w-2xl text-xs leading-5">{base.footer}</div></div></footer>
  </main>;
}
