create table if not exists public.code_requests (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  serial text not null,
  year integer check (year between 1900 and 2100),
  brand text,
  model text,
  phone text,
  email text,
  vin text,
  postal_code text,
  language text not null default 'en',
  status text not null default 'new',
  created_at timestamptz not null default now(),
  priority_sms boolean not null default false,
  payment_status text not null default 'pending',
  payment_provider text,
  amount_total integer,
  currency text,
  paid_at timestamptz,
  paypal_order_id text,
  paypal_capture_id text,
  stereo_code text,
  code_updated_at timestamptz
);

create index if not exists code_requests_created_at_idx
  on public.code_requests (created_at desc);

create index if not exists code_requests_status_idx
  on public.code_requests (status);

alter table public.code_requests enable row level security;

grant select, insert, update, delete on table public.code_requests to service_role;
grant usage, select on sequence public.code_requests_id_seq to service_role;
