create table if not exists public.code_requests (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  serial text not null,
  year integer not null check (year between 1900 and 2100),
  brand text not null,
  model text not null,
  phone text,
  email text,
  vin text,
  language text not null default 'en' check (language in ('en', 'es')),
  status text not null default 'new' check (status in ('new', 'in_progress', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  constraint code_requests_contact_check check (phone is not null or email is not null),
  constraint code_requests_vin_check check (vin is null or vin ~ '^[A-HJ-NPR-Z0-9]{17}$')
);

create index if not exists code_requests_created_at_idx
  on public.code_requests (created_at desc);

create index if not exists code_requests_status_idx
  on public.code_requests (status);

alter table public.code_requests enable row level security;

grant select, insert, update, delete on table public.code_requests to service_role;
grant usage, select on sequence public.code_requests_id_seq to service_role;
