export const metadata = {
  title: "Términos y condiciones | Sorteos entre amigos",
};

export default function TermsPage() {
  return <main className="min-h-screen bg-[#f4efe4] text-[#111]">
    <header className="border-b-2 border-black bg-[#111] text-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5"><a href="/" className="font-black uppercase tracking-[.14em]">← Volver a sorteos</a><span className="text-xs font-black uppercase tracking-[.18em] text-amber-400">Información legal</span></div></header>
    <article className="mx-auto max-w-5xl px-5 py-12">
      <div className="rounded-3xl border-2 border-black bg-amber-400 p-7 shadow-[7px_7px_0_#111]"><div className="text-xs font-black uppercase tracking-[.2em]">Bases generales</div><h1 className="mt-3 text-4xl font-black uppercase sm:text-6xl">Términos y condiciones</h1><p className="mt-5 max-w-3xl font-semibold leading-7">Estas condiciones regulan el uso de la plataforma y complementan las bases particulares publicadas para cada rifa. Cuando una rifa tenga reglas específicas, esas reglas se mostrarán antes de participar.</p></div>

      <div className="mt-10 space-y-8 rounded-3xl border-2 border-black bg-white p-7 sm:p-10">
        <Section n="01" title="Aceptación y elegibilidad"><p>Al apartar o pagar boletos, la persona participante declara haber leído estas condiciones y las bases de la rifa correspondiente. La participación es únicamente para personas que cumplan la edad mínima y los requisitos legales aplicables en su lugar de residencia. La administración podrá solicitar información razonable para confirmar identidad, mayoría de edad o entrega del premio.</p></Section>
        <Section n="02" title="Emisión, precio y promociones"><p>Cada rifa publicará su cantidad máxima de números o emisión, precio por boleto, premio, fecha o referencia del sorteo y, cuando existan, promociones o descuentos por cantidad. Los descuentos se calculan conforme a la configuración vigente al momento de crear la reserva.</p></Section>
        <Section n="03" title="Selección y apartado de números"><p>Los números pueden seleccionarse manualmente o mediante la máquina de la suerte. Una reserva bloquea temporalmente los números elegidos durante el periodo indicado en la plataforma, normalmente dos horas. Una reserva no equivale a un boleto pagado.</p></Section>
        <Section n="04" title="Reservas vencidas"><p>Cuando transcurre el tiempo de apartado sin confirmación de pago, la solicitud pasa a estado de no pagada. Los números no se liberan automáticamente: la administración revisa cada caso y puede liberarlos manualmente para que vuelvan a estar disponibles. El historial de la solicitud se conserva.</p></Section>
        <Section n="05" title="Pagos y cuentas autorizadas"><p>Los pagos deben realizarse únicamente a las cuentas mostradas dentro de la plataforma o comunicadas por los canales oficiales. El participante es responsable de revisar beneficiario, banco, cuenta o CLABE, importe y concepto antes de transferir. Un pago enviado a una cuenta distinta puede requerir revisión manual.</p></Section>
        <Section n="06" title="Comprobantes y confirmación"><p>El comprobante puede cargarse en la plataforma y, cuando la rifa lo permita, enviarse por WhatsApp. La imagen del comprobante por sí sola no constituye prueba definitiva de pago. La administración puede revisar monto, fecha, banco, referencia, clave de rastreo y otros datos, y puede apoyarse en herramientas automáticas o de inteligencia artificial. La confirmación final depende de que el pago pueda validarse por medios confiables.</p></Section>
        <Section n="07" title="Boletos pagados"><p>Los números se consideran pagados cuando la plataforma o la administración cambia expresamente la solicitud al estado de pago confirmado. Antes de ese momento permanecen como reservados, en revisión o no pagados, según corresponda.</p></Section>
        <Section n="08" title="Determinación del ganador"><p>Cada rifa indicará con anticipación el sorteo oficial de Lotería Nacional que se utilizará como referencia. La regla publicada establecerá cómo las últimas cifras del premio principal se relacionan con la emisión de boletos. Para ser elegible, el número debe corresponder a un boleto emitido y confirmado como pagado conforme a las bases de esa rifa.</p><p className="mt-3">Si el resultado no corresponde a un boleto válido y pagado, o cae fuera de la emisión publicada, la administración anunciará una nueva fecha o referencia oficial para repetir la misma dinámica. Cualquier cambio deberá comunicarse antes de aplicar la nueva referencia.</p></Section>
        <Section n="09" title="Publicación y evidencia"><p>Las rifas finalizadas permanecerán registradas en el historial de la plataforma. Cuando corresponda, podrán publicarse número ganador, nombre del ganador con el alcance permitido, referencia del sorteo, evidencia de transmisión o entrega del premio. El objetivo es conservar trazabilidad y credibilidad sin publicar datos personales innecesarios.</p></Section>
        <Section n="10" title="Cambios, cancelaciones y devoluciones"><p>Si por una causa justificada fuera necesario modificar una fecha, premio o condición esencial, la administración deberá comunicarlo por sus canales oficiales. Las devoluciones, cuando procedan, se resolverán conforme a las bases particulares, la situación concreta y la normativa aplicable.</p></Section>
        <Section n="11" title="Uso indebido y fraude"><p>Se podrán rechazar, suspender o revisar solicitudes cuando existan indicios razonables de comprobantes alterados, datos falsos, duplicidad, abuso de promociones, intentos de manipular la disponibilidad de números o cualquier otra conducta que comprometa la integridad del sorteo.</p></Section>
        <Section n="12" title="Datos personales"><p>Los datos proporcionados se utilizan para gestionar reservas, verificar pagos, contactar participantes, emitir comprobantes o boletos, atender aclaraciones y entregar premios. La plataforma debe aplicar medidas razonables de seguridad y limitar la publicación de datos a lo necesario para la transparencia del sorteo.</p></Section>
        <Section n="13" title="Regulación aplicable"><p>La organización de cada rifa es responsabilidad de su operador y debe realizarse conforme a los permisos, avisos, obligaciones fiscales y demás disposiciones que resulten aplicables. La publicación en este sitio no sustituye autorizaciones exigidas por la autoridad competente.</p></Section>
        <Section n="14" title="Actualizaciones"><p>Estas condiciones pueden actualizarse para reflejar cambios operativos o legales. La versión aplicable a una participación será la que se encuentre publicada al momento de crear la reserva, junto con las bases particulares de la rifa correspondiente.</p></Section>
      </div>

      <div className="mt-8 rounded-2xl border-2 border-black bg-[#111] p-6 text-sm leading-7 text-slate-300"><b className="text-white">Nota:</b> este texto es una base operativa original para la plataforma y debe revisarse con asesoría jurídica antes de utilizarse como versión legal definitiva o antes de operar sorteos que requieran autorización.</div>
    </article>
  </main>;
}

function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}) { return <section className="grid gap-4 border-b border-black/15 pb-7 last:border-0 last:pb-0 sm:grid-cols-[64px_1fr]"><div className="flex h-12 w-12 items-center justify-center rounded-full border-2 border-black bg-amber-300 text-sm font-black">{n}</div><div><h2 className="text-xl font-black uppercase">{title}</h2><div className="mt-3 leading-7 text-slate-700">{children}</div></div></section>; }
